language: java

cache:
  directories:
    - $HOME/.m2

before_cache:
  - rm -rf $HOME/.m2/repository/org/keycloak
  - find $HOME/.m2 -name *.lastUpdated -delete

env:
  global:
    - MAVEN_SKIP_RC=true
    - MAVEN_OPTS="-Xms512m -Xmx2048m"
  matrix:
    - TESTS=group1
    - TESTS=group2
    - TESTS=group3
    - TESTS=group4
    - TESTS=adapter
    - APP_SERVER=wildfly AUTH_SERVER=wildfly TESTS=adapter-arquillian
    - APP_SERVER=wildfly AUTH_SERVER=wildfly TESTS=adapter-examples-arquillian
    - APP_SERVER=tomcat9 AUTH_SERVER=wildfly TESTS=adapter-arquillian
    - APP_SERVER=tomcat9 AUTH_SERVER=wildfly TESTS=adapter-examples-arquillian
    # Fuse only has tests for examples, the next line is hence commented out intentionally
    # - APP_SERVER=fuse63 AUTH_SERVER=wildfly TESTS=adapter-arquillian
    - APP_SERVER=fuse63 AUTH_SERVER=wildfly TESTS=adapter-examples-arquillian
    - TESTS=old

jdk:
  - oraclejdk8

before_script:
  - export MAVEN_SKIP_RC=true

install:
  - travis_wait 60 mvn install -Pdistribution -DskipTests=true -B -V -q

script:
  - ./travis-run-tests.sh "$TESTS" "$APP_SERVER" "$AUTH_SERVER"

sudo: false
