name: Keycloak CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        run: mvn clean install -B -DskipTests
      - name: Run base tests - undertow I
        run: bash -c 'I=1; while [[ $I -lt 100 ]] && mvn clean install -B -f testsuite/integration-arquillian/tests/base/pom.xml -Dkeycloak.client.provider=map -Dkeycloak.logging.level=debug "-Dtest=org.keycloak.testsuite.a*.*Test"; do I=$[$I+1] ; done'

